---
clusters:
  - name: tools
    auth:
      type: serviceaccount

  - name: demo
    auth:
      type: agent
      url: https://demo.logalty.com/gitbot-agent

security:
  groups:
    - name: testing
      users:
        - david.gonzalez@logalty.com
  policy:
    - repository: https://bitbucket.org/firmapro/kubernetes.git
      filepattern: ["overlays/test/**", ""]
      minApproved: 1
  rules:
    - repository: https://bitbucket.org/firmapro/kubernetes.git
      filepattern: ["overlays/test/**", ""]
      action: ["lock", "unlock"]
      group: ["testing"]
      user:
        - miguel.lopez@logalty.com
