package internal

import (
	"fmt"
	"log/slog"
	"regexp"
	"sort"
	"strings"

	"gitbot/internal/types"
)

// action represents the kind of operation derived from a PR event.
type action int

const (
	lockAction action = iota
	unlockAction
	helpAction
	unknownAction
)

// EventProcess returns a ProcessFn that is the core event-processing use case.
// It determines the action (lock or unlock) from the event, finds matching ArgoCD
// applications via manager, validates the PR state, and applies the operation.
//
// Returns nil response when the event should be silently ignored (unknown action, no apps found).
func EventProcess(manager types.AppManager) types.ProcessFn {
	return func(e types.Event) (*types.EventResponse, bool) {
		slog.Info("EventProcess: processing event", "type", e.Type, "actorID", e.ActorID, "actorName", e.ActorName, "repository", e.Repository)

		act, env, appname, force := parseAction(e)
		if act == unknownAction || env == nil {
			return nil, false
		}

		switch act {
		case helpAction:
			apps, err := manager.List()
			if err != nil {
				slog.Error("EventProcess: failed to list apps", "error", err)
				return nil, false
			}
			envs := uniqueEnvs(filterByRepo(apps, e.Repository))
			return &types.EventResponse{Environments: envs}, false

		case lockAction:
			apps, err := manager.List()
			if err != nil {
				slog.Error("EventProcess: failed to list apps", "error", err)
				return nil, false
			}

			apps = filterByRepoAndFiles(apps, e.Repository, e.PullRequest.FilesChanged)
			apps = filterByEnv(apps, *env)
			apps = filterByAppName(apps, *appname)

			if len(apps) == 0 {
				slog.Info("EventProcess: no matching apps found")
				return nil, false
			}

			if e.PullRequest.Approved == 0 && e.PullRequest.Reviewers != 0 {
				return &types.EventResponse{Success: false, Message: "You need at least one approval from a reviewer"}, false
			}
			if e.PullRequest.RequestChanged > 0 {
				return &types.EventResponse{Success: false, Message: "One of the reviewers has requested changes"}, false
			}
			if e.PullRequest.CommitsBehind > 0 {
				return &types.EventResponse{
					Success: false,
					Message: fmt.Sprintf("This pull request is %d commits behind '%s', sync your branch!", e.PullRequest.CommitsBehind, e.PullRequest.DestinationBranch),
				}, false
			}

			return applyLock(manager, e.PullRequest, apps, force), false

		case unlockAction:
			apps, err := manager.List()
			if err != nil {
				slog.Error("EventProcess: failed to list apps", "error", err)
				return nil, false
			}

			// Collect apps currently locked by this PR.
			var locked []types.Application
			for _, a := range apps {
				if a.PullRequestId == e.PullRequest.Id {
					locked = append(locked, a.Sanitize())
				}
			}

			locked = filterByEnv(locked, *env)
			locked = filterByAppName(locked, *appname)

			if len(locked) == 0 {
				slog.Info("EventProcess: no matching apps found for unlock")
				return nil, false
			}

			return applyUnlock(manager, e, locked), false
		}

		return nil, false
	}
}

// parseAction extracts the action (lock/unlock), target environment, app name, and force flag
// from a PR event. Returns unknownAction and nil pointers when the event carries no command
// or was generated by the bot itself.
func parseAction(e types.Event) (action, *string, *string, bool) {
	env := "all"
	appname := "all"

	if e.BotGenerated {
		return unknownAction, nil, nil, false
	}

	switch e.Type {
	case types.EventTypeOpened:
		return helpAction, &env, &appname, false

	case types.EventTypeDeclined, types.EventTypeMerged:
		return unlockAction, &env, &appname, false

	case types.EventTypeCommented:
		filter := regexp.MustCompile(`(?i)(/|#)(argo|flux|bot)\s(lock|deploy|test|unlock|undeploy|rollback|help)(?: (\w+))?(?: ([- \w]+?))?(?:\s+--force)?\s*$`).
			FindStringSubmatch(e.Comment)
		if len(filter) <= 3 {
			break
		}
		force := strings.Contains(strings.ToLower(e.Comment), "--force")
		command := filter[3]
		if len(filter) > 4 && filter[4] != "" {
			env = strings.ToLower(filter[4])
		}
		if len(filter) > 5 && filter[5] != "" {
			appname = strings.TrimSpace(strings.ToLower(filter[5]))
		}
		switch strings.ToUpper(command) {
		case "LOCK", "DEPLOY", "TEST":
			return lockAction, &env, &appname, force
		case "UNLOCK", "UNDEPLOY", "ROLLBACK":
			return unlockAction, &env, &appname, false
		case "HELP":
			return helpAction, &env, &appname, false
		}
	}

	return unknownAction, nil, nil, false
}

// applyLock locks all provided apps to the PR's source branch.
// Returns a failed response if any app has a branch mismatch.
// When force is true, apps locked by another PR are unlocked first and then re-locked by this PR.
func applyLock(manager types.AppManager, pr types.PullRequest, apps []types.Application, force bool) *types.EventResponse {
	resp := types.EventResponse{Success: true}

	anyBranchMismatch := false

	for _, a := range apps {
		switch {
		case a.Locked && a.PullRequestId != pr.Id && !force:
			resp.Summary = append(resp.Summary, types.EventAppStatus{
				Name:    a.Name,
				Cluster: a.Cluster,
				Message: fmt.Sprintf("This app is blocked by another pr (%d)", a.PullRequestId),
			})
		case a.Locked && a.PullRequestId != pr.Id && force:
			resp.Summary = append(resp.Summary, types.EventAppStatus{
				Name:    a.Name,
				Cluster: a.Cluster,
				Message: fmt.Sprintf("Stealing lock from pr %d", a.PullRequestId),
			})
		case a.Locked:
			resp.Summary = append(resp.Summary, types.EventAppStatus{Name: a.Name, Cluster: a.Cluster, Message: "Locked"})
		case a.Branch != pr.DestinationBranch:
			anyBranchMismatch = true
			resp.Summary = append(resp.Summary, types.EventAppStatus{
				Name:    a.Name,
				Cluster: a.Cluster,
				Message: fmt.Sprintf("App with branch '%s' dont match with pull request target branch '%s')", a.Branch, pr.DestinationBranch),
			})
		default:
			resp.Summary = append(resp.Summary, types.EventAppStatus{Name: a.Name, Cluster: a.Cluster, Message: "Unlocked"})
		}
	}

	// When not forcing, any lock-by-another or branch-mismatch blocks the whole operation.
	anyLockedByAnother := false
	if !force {
		for _, a := range apps {
			if a.Locked && a.PullRequestId != pr.Id {
				anyLockedByAnother = true
				break
			}
		}
	}

	if anyBranchMismatch || anyLockedByAnother {
		resp.Success = false
		return &resp
	}

	for i, a := range apps {
		// Force-steal: transition to unlocked state in domain only, then lock in one API call.
		if force && a.Locked && a.PullRequestId != pr.Id {
			slog.Info("EventProcess: force-stealing lock", "app", a.Name, "from_pr", a.PullRequestId, "to_pr", pr.Id)
			a = a.Unlock()
		}

		if !a.Locked {
			slog.Info("EventProcess: locking app", "app", a.Name)
			if err := manager.Lock(a, pr.SourceBranch, pr.Id); err != nil {
				slog.Error("EventProcess: failed to lock app", "app", a.Name, "error", err)
				resp.Success = false
				resp.Summary[i].Message = "Error at lock application"
				return &resp
			}
			resp.Summary[i].Message = "Locked"
		}
	}

	return &resp
}

// applyUnlock unlocks apps that are locked by the given PR.
// Returns nil for merge/decline events when all unlocks succeed (silent operation).
func applyUnlock(manager types.AppManager, e types.Event, apps []types.Application) *types.EventResponse {
	resp := types.EventResponse{Success: true}

	anyLockedByMe := false
	for _, a := range apps {
		if a.Locked {
			anyLockedByMe = true
		}
		resp.Summary = append(resp.Summary, types.EventAppStatus{
			Name:    a.Name,
			Cluster: a.Cluster,
			Message: lockedStatus(a.Locked),
		})
	}

	if !anyLockedByMe {
		if e.Type == types.EventTypeMerged || e.Type == types.EventTypeDeclined {
			return nil
		}
		return &resp
	}

	for i, a := range apps {
		if !a.Locked {
			continue
		}
		if err := manager.Unlock(a); err != nil {
			slog.Error("EventProcess: failed to unlock app", "app", a.Name, "cluster", a.Cluster, "error", err)
			resp.Success = false
			resp.Summary[i].Message = "Error at unlock application"
			return &resp
		}
		resp.Summary[i].Message = "Unlocked"
	}

	if resp.Success && (e.Type == types.EventTypeMerged || e.Type == types.EventTypeDeclined) {
		return nil
	}

	return &resp
}

// ── Pure helper functions ─────────────────────────────────────────────────────

// filterByRepo returns apps whose repository matches repo.
func filterByRepo(apps []types.Application, repo string) []types.Application {
	var result []types.Application
	for _, a := range apps {
		if a.Repository == repo {
			result = append(result, a)
		}
	}
	return result
}

// uniqueEnvs returns the sorted, deduplicated list of non-empty environments
// present in the given apps.
func uniqueEnvs(apps []types.Application) []string {
	seen := make(map[string]struct{})
	var envs []string
	for _, a := range apps {
		if a.Environment != "" {
			if _, ok := seen[a.Environment]; !ok {
				seen[a.Environment] = struct{}{}
				envs = append(envs, a.Environment)
			}
		}
	}
	sort.Strings(envs)
	return envs
}

// ── Pure filter functions ─────────────────────────────────────────────────────

// filterByEnv returns apps whose environment matches env, or all apps when env is "all".
func filterByEnv(apps []types.Application, env string) []types.Application {
	var result []types.Application
	for _, a := range apps {
		if strings.EqualFold(a.Environment, env) || env == "all" {
			result = append(result, a.Sanitize())
		}
	}
	return result
}

// filterByAppName returns apps whose name matches name, or all apps when name is "all".
func filterByAppName(apps []types.Application, name string) []types.Application {
	var result []types.Application
	for _, a := range apps {
		if strings.EqualFold(a.Name, name) || name == "all" {
			result = append(result, a.Sanitize())
		}
	}
	return result
}

// filterByRepoAndFiles returns apps that own at least one of the changed files in repo.
func filterByRepoAndFiles(apps []types.Application, repo string, files []string) []types.Application {
	var result []types.Application
	for _, a := range apps {
		if matchByRepoAndFiles(a, repo, files) {
			result = append(result, a.Sanitize())
		}
	}
	return result
}

// matchByRepoAndFiles reports whether any of the changed files falls under one
// of the application's registered paths in the given repository.
func matchByRepoAndFiles(a types.Application, repo string, files []string) bool {
	if a.Repository != repo {
		return false
	}
	for _, file := range files {
		for _, path := range a.Paths {
			if strings.Contains(normalizePath(file), normalizePath(path)) {
				return true
			}
		}
	}
	return false
}

// normalizePath canonicalises a file or directory path so that prefix-matching works
// correctly regardless of leading "./" or missing leading/trailing slash variants.
func normalizePath(path string) string {
	if len(path) > 1 && path[0] == '.' && path[1] == '/' {
		path = strings.TrimPrefix(path, ".")
	}
	if len(path) > 0 && path[0] != '/' {
		path = "/" + path
	}
	if len(path) > 0 && path[len(path)-1] != '/' {
		path += "/"
	}
	return path
}

// lockedStatus returns the human-readable lock state for use in response messages.
func lockedStatus(locked bool) string {
	if locked {
		return "Locked"
	}
	return "Unlocked"
}
